services:
  app:
    image: bloglist-frontend
    build:
      context: ./bloglist-frontend/ # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 5000:3000
    container_name: bloglist-frontend # This will name the container todo-front-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./bloglist-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./bloglist-backend/mongo_data:/data/db
  
  server:                    # The name of the service, can be anything
    image: bloglist-backend   # Declares which image to use
    build:
      context: ./bloglist-backend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:                # Declares the ports to publish
      - 3000:3000    
    container_name: bloglist-backend # This will name the container todo-front-dev  
    environment: 
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database     
      - PORT=3000
      - SECRET=sallaisuus 

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-bloglist
    depends_on:
      - app # wait for the frontend container to be started
      - server    